#!/usr/bin/bash

# Alias
alias cls="clear"
alias pyact="pyenv activate"
alias pydeact="pyenv deactivate"
alias s="subl"
alias n="gnvim"
alias gac="git add . && git commit"
alias gtail="git rev-list --all | tail"
alias xmerge="git merge --no-ff"
alias g="git"

# >>> Version managers

# PYENV
# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Users/towry/.multirust/toolchains/stable/cargo/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH
export RUSTUP_DIST_SERVER="https://mirrors.ustc.edu.cn/rust-static"

# NVM
export NVM_DIR="/Users/towry/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# <<<<

# >>> source
source ~/.dotfiles/source/shutils
# <<<

# >>> Exports
# PATH="/usr/local/bin/vi:$HOME/dev/.tools/depot_tools:$PATH"
# export PATH
# <<<

# eval "$(docker-machine env default)"

[[ -s /Users/towry/.rsvm/rsvm.sh ]] && . /Users/towry/.rsvm/rsvm.sh # This loads RSVM

source ~/.gvm/scripts/gvm
PYTHONPATH="/Users/towry/Projects/mtp:${PYTHONPATH}"
export PYTHONPATH

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export VISUAL=vim
export EDITOR="$VISUAL"
